### ISSUE TITLE
TodoList TypeScript 구조분해할당 type 지정 관련 질문

### ISSUE THREAD

**Issue by bubblyness** [v-park/wanted-pre-onboarding-challenge-fe-1#1]
`interface modalType {
  openDetail: (id: string) => void;
  list: {
    title: string;
    content: string;
    id: string;
    createdAt: string;
    updatedAt: string;
  }[];
  detail: {
    title: string;
    content: string;
    id: string;
    createdAt: string;
    updatedAt: string;
  };
}

export default function TodoList({ openDetail, list, detail }: modalType) {
 `

위 list state는 Array안에 object가 담긴 형태인데 이 부분을 props로 받지 않고 바로 구조분해 할당으로 받아서 사용하고 싶은데 이 부분에서 도움을 받을 수 있을까요?

**Comment by bubblyness** [comment]
위 list state는 Array안에 object가 담긴 형태인데 이 부분을 props로 받지 않고 바로 구조분해 할당으로 받아서 사용하고 싶은데 이 부분에서 도움을 받을 수 있을까요?

**Comment by gliburch** [comment]
@v-park 구조분해 할당에 관한 몇 가지 자료를 찾아보니 '중첩 구조 분해 (Nested Destruction)' 로 불리는 것 같습니다.
질문의 의도를 제대로 파악한건지 모르겠지만, 배열 안에 있는 객체에 대한 구조 분해 할당을 하는 예제 코드를 작성해보았습니다.

참고한 글: https://whitepro.tistory.com/130

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/359443/184467371-c46c4a81-849b-4268-9b2a-e245c7cbbacb.png">

**Comment by bubblyness** [comment]
@gliburch 질문에 답변해주셔서 감사합니다. 팀원과 함께 참고해서 반영해보도록 하겠습니다. @ghbaekdev
